port: 8080

oauth: 
    redirectUrl: http://localhost:8080/auth/callback
    clientId: something
    clientSecret: something

db: 
    user: root
    password: gohtmx
    database: gohtmx
    host: mysql:3306

jwt: 
    secret: secret

twitchChatBot: 
    token: something
    username: something
